import { NextRequest, NextResponse } from "next/server";
import type { Article, ArticleListResponse } from "@/entities/article";

// Mock 데이터
const mockArticles: Article[] = [
  {
    id: "1",
    title: "아이패드 9세대 + 애플펜슬",
    price: 381371,
    location: "로욜라 도서관 1관 앞",
    imageUrl: "https://picsum.photos/seed/1/300/200",
    likeCount: 33,
    chatCount: 8,
    status: "active",
    category: "전자기기",
    description: "상품 1에 대한 설명입니다.",
    userId: "105",
    userName: "user23",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "토익 공식문제집 1000제 세트",
    price: 645442,
    location: "로욜라 도서관 1관 앞",
    imageUrl: "https://picsum.photos/seed/2/300/200",
    likeCount: 1,
    chatCount: 4,
    status: "sold",
    category: "도서",
    description: "상품 2에 대한 설명입니다.",
    userId: "126",
    userName: "user11",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "미니 빔프로젝터",
    price: 328544,
    location: "다산관 1층 로비",
    imageUrl: "https://picsum.photos/seed/3/300/200",
    likeCount: 48,
    chatCount: 4,
    status: "sold",
    category: "전자기기",
    description: "상품 3에 대한 설명입니다.",
    userId: "168",
    userName: "user47",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "공학용 계산기",
    price: 741907,
    location: "PA관 1층",
    imageUrl: "https://picsum.photos/seed/4/300/200",
    likeCount: 43,
    chatCount: 16,
    status: "reserved",
    category: "학용품",
    description: "상품 4에 대한 설명입니다.",
    userId: "200",
    userName: "user37",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "자전거",
    price: 752392,
    location: "우정관 1층 카페",
    imageUrl: "https://picsum.photos/seed/5/300/200",
    likeCount: 49,
    chatCount: 8,
    status: "sold",
    category: "생활용품",
    description: "상품 5에 대한 설명입니다.",
    userId: "181",
    userName: "user24",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "닌텐도 스위치 OLED",
    price: 299761,
    location: "RA관 2층 로비",
    imageUrl: "https://picsum.photos/seed/6/300/200",
    likeCount: 9,
    chatCount: 9,
    status: "sold",
    category: "게임/취미",
    description: "상품 6에 대한 설명입니다.",
    userId: "149",
    userName: "user39",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "소형 냉장고",
    price: 745480,
    location: "J관 2층",
    imageUrl: "https://picsum.photos/seed/7/300/200",
    likeCount: 31,
    chatCount: 6,
    status: "active",
    category: "가구",
    description: "상품 7에 대한 설명입니다.",
    userId: "119",
    userName: "user19",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "기타 앰프",
    price: 487589,
    location: "곤자가 국제학사 1층 로비",
    imageUrl: "https://picsum.photos/seed/8/300/200",
    likeCount: 23,
    chatCount: 3,
    status: "active",
    category: "의류",
    description: "상품 8에 대한 설명입니다.",
    userId: "164",
    userName: "user2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    title: "미니 빔프로젝터",
    price: 137928,
    location: "MA관 2층",
    imageUrl: "https://picsum.photos/seed/9/300/200",
    likeCount: 31,
    chatCount: 16,
    status: "reserved",
    category: "도서",
    description: "상품 9에 대한 설명입니다.",
    userId: "175",
    userName: "user7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    title: "닌텐도 스위치 OLED",
    price: 552687,
    location: "우정관 1층 카페",
    imageUrl: "https://picsum.photos/seed/10/300/200",
    likeCount: 12,
    chatCount: 13,
    status: "sold",
    category: "게임/취미",
    description: "상품 10에 대한 설명입니다.",
    userId: "124",
    userName: "user50",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "11",
    title: "에어팟 프로 2세대",
    price: 962931,
    location: "우정관 1층 카페",
    imageUrl: "https://picsum.photos/seed/11/300/200",
    likeCount: 26,
    chatCount: 5,
    status: "reserved",
    category: "전자기기",
    description: "상품 11에 대한 설명입니다.",
    userId: "155",
    userName: "user19",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    title: "맥북 에어 M1 13인치",
    price: 985321,
    location: "다산관 1층 로비",
    imageUrl: "https://picsum.photos/seed/12/300/200",
    likeCount: 2,
    chatCount: 3,
    status: "active",
    category: "전자기기",
    description: "상품 12에 대한 설명입니다.",
    userId: "120",
    userName: "user48",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    title: "미니 빔프로젝터",
    price: 779096,
    location: "R관 5층 라운지",
    imageUrl: "https://picsum.photos/seed/13/300/200",
    likeCount: 16,
    chatCount: 14,
    status: "sold",
    category: "전자기기",
    description: "상품 13에 대한 설명입니다.",
    userId: "142",
    userName: "user20",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    title: "서강대학교 후드티",
    price: 538582,
    location: "MA관 2층",
    imageUrl: "https://picsum.photos/seed/14/300/200",
    likeCount: 15,
    chatCount: 20,
    status: "sold",
    category: "의류",
    description: "상품 14에 대한 설명입니다.",
    userId: "174",
    userName: "user32",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    title: "공학용 계산기",
    price: 552997,
    location: "AS관 4층 라운지",
    imageUrl: "https://picsum.photos/seed/15/300/200",
    likeCount: 48,
    chatCount: 0,
    status: "active",
    category: "학용품",
    description: "상품 15에 대한 설명입니다.",
    userId: "179",
    userName: "user28",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "16",
    title: "소형 냉장고",
    price: 135739,
    location: "R관 5층 라운지",
    imageUrl: "https://picsum.photos/seed/16/300/200",
    likeCount: 43,
    chatCount: 16,
    status: "sold",
    category: "가구",
    description: "상품 16에 대한 설명입니다.",
    userId: "128",
    userName: "user42",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "17",
    title: "에어팟 프로 2세대",
    price: 976086,
    location: "AS관 4층 라운지",
    imageUrl: "https://picsum.photos/seed/17/300/200",
    likeCount: 13,
    chatCount: 11,
    status: "active",
    category: "의류",
    description: "상품 17에 대한 설명입니다.",
    userId: "169",
    userName: "user40",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "18",
    title: "게이밍 의자",
    price: 588081,
    location: "로욜라 도서관 1관 앞",
    imageUrl: "https://picsum.photos/seed/18/300/200",
    likeCount: 48,
    chatCount: 20,
    status: "reserved",
    category: "가구",
    description: "상품 18에 대한 설명입니다.",
    userId: "193",
    userName: "user10",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "19",
    title: "맥북 에어 M1 13인치",
    price: 884696,
    location: "다산관 1층 로비",
    imageUrl: "https://picsum.photos/seed/19/300/200",
    likeCount: 28,
    chatCount: 15,
    status: "sold",
    category: "전자기기",
    description: "상품 19에 대한 설명입니다.",
    userId: "163",
    userName: "user18",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "20",
    title: "자전거",
    price: 241726,
    location: "MA관 2층",
    imageUrl: "https://picsum.photos/seed/20/300/200",
    likeCount: 34,
    chatCount: 17,
    status: "sold",
    category: "생활용품",
    description: "상품 20에 대한 설명입니다.",
    userId: "189",
    userName: "user29",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  
  // 쿼리 파라미터 추출
  const category = searchParams.get("category");
  const page = parseInt(searchParams.get("page") || "1");
  const limit = parseInt(searchParams.get("limit") || "20");

  // 카테고리 필터링
  let filteredArticles = mockArticles;
  if (category && category !== "전체") {
    filteredArticles = mockArticles.filter(
      (article) => article.category === category
    );
  }

  // 페이지네이션
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedArticles = filteredArticles.slice(startIndex, endIndex);

  const response: ArticleListResponse = {
    items: paginatedArticles,
    pagination: {
      current: page,
      total: filteredArticles.length,
      totalPages: Math.ceil(filteredArticles.length / limit),
      hasNext: endIndex < filteredArticles.length,
      hasPrev: page > 1,
    },
  };

  return NextResponse.json(response);
}
